### ISSUE TITLE
.net8 runtime location not found

### ISSUE THREAD

**Issue by nelsonmorais** [dotnet-outdated/dotnet-outdated#514]
Hi,

I'm using version 4.6.0 that has already support for the .net8 runtime as indicated on #482 , but when I run `dotnet outdated` I get the following error:
```
You must install .NET to run this application.

App: /home/nstm/.dotnet/tools/dotnet-outdated
Architecture: x64
App host version: 8.0.0
.NET location: Not found

Learn more:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=linux-x64&os=ubuntu.22.04&apphost_version=8.0.0
```

However if I run `dotnet ~/.dotnet/tools/.store/dotnet-outdated-tool/4.6.0/dotnet-outdated-tool/4.6.0/tools/net8.0/any/dotnet-outdated.dll` all works as expected.

I do have the .net8 SDK installed on Ubuntu 22.04 on WSL. The DSL was installed using the Microsoft Packages, not the Ubuntu Packages as there's no support for .net8 on the Ubuntu Packages.

Running `dotnet --info` I see:
```
.NET SDK:
 Version:           8.0.100
 Commit:            57efcf1350
 Workload version:  8.0.100-manifests.6c33ef20

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.100/

.NET workloads installed:
 Workload version: 8.0.100-manifests.6c33ef20
There are no installed workloads to display.

Host:
  Version:      8.0.0
  Architecture: x64
  Commit:       5535e31a71

.NET SDKs installed:
  6.0.417 [/usr/share/dotnet/sdk]
  8.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.25 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.25 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

Running `whereis dotnet` shows:
```
dotnet: /usr/bin/dotnet /etc/dotnet /usr/share/dotnet
```

Running `which dotnet` shows:
```
/usr/bin/dotnet
```

Running `ls /usr/bin/dotnet -lha` shows:
```
lrwxrwxrwx 1 root root 22 Oct 31 16:15 /usr/bin/dotnet -> ../share/dotnet/dotnet
```

The `PATH` has the path to where `dotnet` is accessible from, at `/usr/bin`

Any suggestions why running `dotnet outdated` still can't find the .net8 runtime?

**Comment by solrevdev** [comment]
A separate issue but on a windows machine I look after I had an problem where I had a version of dotnet outdated that wasn't in nuget or a really old version etc:

```powershell
Unhandled exception: Microsoft.DotNet.Cli.NuGetPackageDownloader.NuGetPackageNotFoundException: dotnet-outdated::[*, ) is not found in NuGet feeds https://api.nuget.org/v3/index.json, C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\".
   at Microsoft.DotNet.Cli.NuGetPackageDownloader.NuGetPackageDownloader.GetMatchingVersionInternalAsync(String packageIdentifier, IEnumerable`1 packageSources, VersionRange versionRange, CancellationToken cancellationToken)
   at Microsoft.DotNet.Cli.NuGetPackageDownloader.NuGetPackageDownloader.GetBestPackageVersionAsync(PackageId packageId, VersionRange versionRange, PackageSourceLocation packageSourceLocation)
   at Microsoft.DotNet.Cli.ToolPackage.ToolPackageDownloader.<>c__DisplayClass8_0.<InstallPackage>b__0()
   at Microsoft.DotNet.Cli.TransactionalAction.Run[T](Func`1 action, Action commit, Action rollback)
   at Microsoft.DotNet.Tools.Tool.Update.ToolUpdateGlobalOrToolPathCommand.<>c__DisplayClass14_0.<Execute>b__1()
   at Microsoft.DotNet.Tools.Tool.Update.ToolUpdateGlobalOrToolPathCommand.RunWithHandlingInstallError(Action installAction)
   at Microsoft.DotNet.Tools.Tool.Update.ToolUpdateGlobalOrToolPathCommand.Execute()
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
```

I fixed it by: 

Find out what dotnet tools were installed globally:

```bash
dotnet tool list -- global 
```
This returned: 

```bash
dotnet-outdated                         2.11.0          dotnet-outdated
```
So i ran `dotnet tool uninstall --global dotnet-outdated` then `dotnet tool install --global dotnet-outdated-tool --version 4.6.0` and that fixed the issue. 

Maybe check to see what global tools you have installed as first step. 

Hope this helps

**Comment by nelsonmorais** [comment]
Hi @solrevdev 

Thanks for the suggestion. Unfortunately this is not my case as I only have version 4.6.0 installed.

```bash
dotnet toll list --global
```

returns
```bash
Package Id                Version      Commands       
------------------------------------------------------
dotnet-outdated-tool      4.6.0        dotnet-outdated
```

And I have no other tools installed at the project level.

**Comment by solrevdev** [comment]
@nelsonmorais ahh worth a try. the original error about not finding .net 8 points to `App: /home/nstm/.dotnet/tools/dotnet-outdated` is there a global.json in the `nstm` folder or anything like that. maybe a WSL issue. I've run out of talent here I think mate. I'll mull it over and if i think of anything else I'll jump back on and comment.

**Comment by nelsonmorais** [comment]
Hi @solrevdev 

Thanks again for the fast reply. Just in case I've uninstalled and installed again, but still no luck 😞 

If I run just the command `./dotnet-outdated --help` executed from `~/.dotnet/tools` (aka: `/home/nstm/.dotnet/tools`) I receive the same error. Looks to me that there's a mismatch between version 8.0.0 on the App Host and version 8.0.100 that is the one installed by the SDK.

I don't have any global.json, but I just tried to create one and placed it at `~/.dotnet/tools` to force the sdk-runtime to be 8.0.100, but also that didn't work.

I guess for now the only workaround is to use the command `dotnet ~/.dotnet/tools/.store/dotnet-outdated-tool/4.6.0/dotnet-outdated-tool/4.6.0/tools/net8.0/any/dotnet-outdated.dll`.

The problem seems to be just on the App Host at `~/.dotnet/tools` as running the `net8.0` `dotnet-outdated.dll` directly runs without issues.

Thanks for the support!

**Comment by nelsonmorais** [comment]
After running into more issues with the dotnet runtime not being found, I finally found the problem and the solution, so sharing here in case others face the same issue.

My issue was:
- Long time ago I had installed dotnet 6 from the Ubuntu packages 
- Recently I re-installed dotnet 6 and 8 using the Microsoft packages following the info at https://learn.microsoft.com/en-us/dotnet/core/install/linux-package-mixup?pivots=os-linux-redhat#i-need-a-version-of-net-that-isnt-provided-by-my-linux-distribution
- The issue is the the link above doesn't mention anything about the files `/etc/dotnet/install_location` and `/etc/dotnet/install_location_x86`

Solution:
- If there was already a previous installation of dotnet using the Ubuntu packages, then the files `/etc/dotnet/install_location` and `/etc/dotnet/install_location_x86` need to be updated to point to `/etc/share/dotnet`, otherwise the dotnet runtime is not found as the files above are still pointing to `/etc/bin/dotnet` as originally set by the dotnet installation using the Ubuntu packages.

Here's a link that helped me to figure this out: https://github.com/dotnet/runtime/issues/82843#issuecomment-1450695895

With this solved, I'll also close this issue.
